[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

# 更新をすぐ反映させる
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
